import { error } from '@sveltejs/kit';
import { BYPASS_TOKEN, DIRECTUS_URL, DIRECTUS_TOKEN } from '$env/static/private';

/** @type {import('./$types').PageLoad} */
export async function load({ params, request }) {
  try {    
    const url = new URL(`${DIRECTUS_URL}/items/pages`);
    url.searchParams.append('filter[url][_eq]', `/${params.page}`);
    url.searchParams.append('fields[]', 'content.item:blocks.*');

    console.log('url', params.page);
    const res = await fetch(url, {
      method: 'get',
      headers: {
        Authorization: `Bearer ${DIRECTUS_TOKEN}`
      },
    });
    const { data } = await res.json();
    let [pagedata] = (data || []);

    pagedata.content = await Promise.all(pagedata.content.map(async (e) => {
      if (e.item.type === 'rental_card') {
        const url = new URL(`${DIRECTUS_URL}/items/rentals/${e.item.entity}`);
        const res = await fetch(url, {
          method: 'get',
          headers: {
            Authorization: `Bearer ${DIRECTUS_TOKEN}`
          },
        });
        e.item.entity = (await res.json()).data;
      }
      if (e.item.type === 'slider') {
        const url = new URL(`${DIRECTUS_URL}/items/blocks/${e.item.id}`);
        url.searchParams.append('fields[]', 'type,image,images.*');
        const res = await fetch(url, {
          method: 'get',
          headers: {
            Authorization: `Bearer ${DIRECTUS_TOKEN}`
          },
        });
        e.item = (await res.json()).data;
      }
      return e;
    }));
        return {
          data: pagedata
        };
  } catch (err) {
    throw error(404, 'This page does not exist');
  }
}

export const config = {
  isr: {
    // Random token that can be provided to bypass the cached version of the page with a __prerender_bypass=<token> cookie. Allows rendering content at request time for this route.
    bypassToken: BYPASS_TOKEN,

    // Expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
    // Setting the value to `false` means it will never expire.
    expiration: 60,
  },
};